# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.4
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: riteshkatore2005@gmail.com
author_name: ritesh
cloud_provider: none
contract_name: tenderfi
deployment_language: python
preset_name: production
project_name: TenderFi

